title: opencode ;; workdir: /home/mtozan/projects/portfolio ;; command: opencode
title: gemini ;; workdir: /home/mtozan/projects/portfolio ;; command: gemini
title: agy ;; workdir: /home/mtozan/projects/portfolio ;; command: agy
