title: opencode ;; workdir: /home/mtozan/projects/portfolio ;; command: opencode
title: gemini ;; workdir: /home/mtozan/projects/portfolio ;; command: gemini
title: agy ;; workdir: /home/mtozan/projects/portfolio ;; command: agy
title: copilot ;; workdir: /home/mtozan/projects/portfolio ;; command: copilot
title: npm run dev ;; workdir: /home/mtozan/projects/portfolio ;; command: npm run dev
